package `fun`.dogon.note

import android.graphics.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.ui.graphics.vector.ImageVector

val iconKeys=listOf("note","work","idea","person","cart","heart","book","star","home","music","travel","code","gift","calendar","check","coffee","fitness","money","key","flag","pet","sun","moon","plant","school","science","language","palette","camera","movie","headphones","phone","email","map","place","restaurant","cake","sports","game","car","bike","train","flight","hotel","beach","shopping","wallet","receipt","schedule","alarm","bookmark","folder","cloud","download","upload","link","lock","favorite","bolt")
val iconLabels=listOf("Not","İş","Fikir","Kişisel","Alışveriş","Kalp","Kitap","Yıldız","Ev","Müzik","Seyahat","Kod","Hediye","Takvim","Görev","Kahve","Spor","Para","Anahtar","Bayrak","Hayvan","Güneş","Ay","Doğa","Okul","Bilim","Dil","Tasarım","Kamera","Film","Kulaklık","Telefon","E-posta","Harita","Konum","Yemek","Pasta","Spor","Oyun","Araba","Bisiklet","Tren","Uçuş","Otel","Tatil","Alışveriş","Cüzdan","Fiş","Saat","Alarm","Yer imi","Klasör","Bulut","İndir","Yükle","Bağlantı","Kilit","Favori","Enerji")
fun noteIcon(key:String):ImageVector=when(key) {
    "work"->Icons.Outlined.WorkOutline;"idea"->Icons.Outlined.Lightbulb;"person"->Icons.Outlined.PersonOutline;"cart"->Icons.Outlined.ShoppingCart;"heart"->Icons.Outlined.FavoriteBorder;"book"->Icons.Outlined.MenuBook;"star"->Icons.Outlined.StarOutline;"home"->Icons.Outlined.Home;"music"->Icons.Outlined.MusicNote;"travel"->Icons.Outlined.Luggage;"code"->Icons.Outlined.Code;"gift"->Icons.Outlined.CardGiftcard;"calendar"->Icons.Outlined.CalendarMonth;"check"->Icons.Outlined.CheckCircleOutline;"coffee"->Icons.Outlined.Coffee;"fitness"->Icons.Outlined.FitnessCenter;"money"->Icons.Outlined.Payments;"key"->Icons.Outlined.Key;"flag"->Icons.Outlined.Flag;"pet"->Icons.Outlined.Pets;"sun"->Icons.Outlined.WbSunny;"moon"->Icons.Outlined.Bedtime;"plant"->Icons.Outlined.Eco;"school"->Icons.Outlined.School;"science"->Icons.Outlined.Science;"language"->Icons.Outlined.Language;"palette"->Icons.Outlined.Palette;"camera"->Icons.Outlined.PhotoCamera;"movie"->Icons.Outlined.Movie;"headphones"->Icons.Outlined.Headphones;"phone"->Icons.Outlined.Phone;"email"->Icons.Outlined.Email;"map"->Icons.Outlined.Map;"place"->Icons.Outlined.Place;"restaurant"->Icons.Outlined.Restaurant;"cake"->Icons.Outlined.Cake;"sports"->Icons.Outlined.SportsBasketball;"game"->Icons.Outlined.SportsEsports;"car"->Icons.Outlined.DirectionsCar;"bike"->Icons.Outlined.DirectionsBike;"train"->Icons.Outlined.Train;"flight"->Icons.Outlined.Flight;"hotel"->Icons.Outlined.Hotel;"beach"->Icons.Outlined.BeachAccess;"shopping"->Icons.Outlined.ShoppingBag;"wallet"->Icons.Outlined.AccountBalanceWallet;"receipt"->Icons.Outlined.ReceiptLong;"schedule"->Icons.Outlined.Schedule;"alarm"->Icons.Outlined.Alarm;"bookmark"->Icons.Outlined.BookmarkBorder;"folder"->Icons.Outlined.FolderOpen;"cloud"->Icons.Outlined.Cloud;"download"->Icons.Outlined.Download;"upload"->Icons.Outlined.Upload;"link"->Icons.Outlined.Link;"lock"->Icons.Outlined.Lock;"favorite"->Icons.Outlined.Favorite;"bolt"->Icons.Outlined.Bolt;else->Icons.Outlined.Description
}
fun iconBitmap(key:String,color:String):Bitmap {
    val res=Repo.context.resources.getIdentifier("ic_$key","drawable",Repo.context.packageName).takeIf { it!=0 }?:R.drawable.ic_note
    val drawable=Repo.context.getDrawable(res)!!.mutate();drawable.setTint(Color.parseColor(color));val b=Bitmap.createBitmap(96,96,Bitmap.Config.ARGB_8888);drawable.setBounds(8,8,88,88);drawable.draw(Canvas(b));return b
}
